server:
  port: 80


spring:
  datasource:
    url: jdbc:postgresql://49.232.252.164:5432/socialdatabase
    username: socialapp
    password: Social020102
    driver-class-name: org.postgresql.Driver