server:
  port: 80


spring:
  datasource:
    url: jdbc:postgresql://39.106.56.3:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mvc:
    view:
      suffix: .html
      prefix: /
